### ISSUE TITLE
Depending parameters

### ISSUE THREAD

**Issue by beseder42** [jatoben/CommandLine#106]
Given the following situation: My Tool can do two jobs: A and B. Job A needs parameters a and b, Job B needs parameters c and d. 

So if the user wants job A I want parameters a and b required. If he wants job B I want parameters c and d required. 

How would I handle theses depending parameters nicely, meaning without lots of `if` and custom messages of required parameters.

**Comment by jatoben** [comment]
This repository is being archived. See https://github.com/jatoben/CommandLine/issues/111.
