### ISSUE TITLE
This project will be archived soon

### ISSUE THREAD

**Issue by jatoben** [jatoben/CommandLine#111]
Hi folks,

If you've been watching this repository, you can tell that I haven't had time to work on this for quite a while. I plan to [archive it in the near future](https://help.github.com/articles/archiving-repositories/) to avoid any confusion.

If anyone has an active fork and would like to pick up the mantle—@benoit-pereira-da-silva, @beltex, or @pdesantis maybe?—I'd be happy to point to your fork(s) for anyone who's looking for a maintained version.

Thanks to everyone who's contributed!

**Comment by benoit-pereira-da-silva** [comment]
Hi ben i do use a lot CommandLine and will maintain my own flavor for long term support. I m not sure it will satisfy your community needs...

**Comment by jatoben** [comment]
Thanks @benoit-pereira-da-silva. If you’d like me to add a link to your fork when I archive this repo, let me know.

**Comment by benoit-pereira-da-silva** [comment]
@jatoben my fork is available at https://github.com/Bartlebys/CommandLine

**Comment by benoit-pereira-da-silva** [comment]
@jatoben finally, as Bartleby used to say  "i would prefer not to".  I m considering moving all my CLI stuffs to `go` in 2019.  Thanks for the proposition.

**Comment by jatoben** [comment]
No problem @benoit-pereira-da-silva, thanks again for letting me know.
