### ISSUE TITLE
Carthage & Cocoapods support?

### ISSUE THREAD

**Issue by daniel-beard** [jatoben/CommandLine#15]
- Both Carthage and Cocoapods support building swift code, it would be nice to add support for both.

**Comment by tkrajacic** [comment]
This wouldn't make sense as it is impossible to build command line tools with Swift that link to frameworks.

**Comment by daniel-beard** [comment]
Ah, got it. I wasn't aware of that limitation.

**Comment by beltex** [comment]
Hi @daniel-beard!

For Carthage, nothing needs to be done on the library side (this project), its just a matter of adding it to your project (Cartfile + Xcode project settings).

@tkrajacic is correct in that command line tool Xcode projects in Swift currently have the language runtime statically linked (to create a standalone binary), and thus frameworks (`.dylibs`) that Carthage generates fail to link as they cannot _"see"_ the language runtime. See [SwiftInFlux/Runtime Dynamic Libraries](https://github.com/ksm/SwiftInFlux#runtime-dynamic-libraries) for more. However, Carthage adopts a clever workaround, which is described here: https://github.com/Carthage/Carthage/issues/287#issuecomment-71463248. Projects like [SourceKitten](https://github.com/jpsim/SourceKitten) & [SwiftLint](https://github.com/realm/SwiftLint) adopt this technique. In fact, Carthage itself does this :) The key magic for all this can be see in the `Makefile` of any of the projects just mentioned. Same concept described [here](http://colemancda.github.io/programming/2015/02/12/embedded-swift-frameworks-osx-command-line-tools/) as well.

As for CocoaPods, see #6. I'm not sure how they handle this case however.
