### ISSUE TITLE
shortFlag XOR longFlag possibility

### ISSUE THREAD

**Issue by beltex** [jatoben/CommandLine#22]
One thing that happens with having `shortFlag` be mandatory is that since its only a single character, you quickly get collisions, and thus are forced to use random characters for an option (`-y, --check-file`). I think in such a case, it would be better to have the option to specify only a `longFlag`. You could make a case for the other direction too of course, thus I'm thinking it be useful to have the ability to exclusively choose a `shortFlag` or `longFlag` for an `Option`.

**Comment by jatoben** [comment]
@beltex In general I think having both short and long flags is the best choice, but I suppose there are cases where it doesn't make sense. I'll see if I can tackle this without having to drop optionals all over the place.

**Comment by beltex** [comment]
@jatoben Awesome, thanks! :)
