### ISSUE TITLE
Stray values support?

### ISSUE THREAD

**Issue by brunophilipe** [jatoben/CommandLine#23]
It would be interesting for me to have a default stray value not associated with any flag, let's say:

`$ readfile --type=pdf ~/Documents/myfile.pdf`

Perhaps I am missing something.

Thanks for the awesome tool! :)

**Comment by jatoben** [comment]
This would definitely be useful, thanks for the suggestion.

**Comment by samskiter** [comment]
:+1:

**Comment by aleph7** [comment]
:+1:

**Comment by klaas** [comment]
+1
