### ISSUE TITLE
String Option with default value

### ISSUE THREAD

**Issue by dehlen** [jatoben/CommandLine#31]
Hello,

I got this code sample:
```swift 
let cli = CommandLine()

let deploy = StringOption(shortFlag: "d", longFlag: "deploy",
  helpMessage: "Deploys a plugin, color scheme or template from given directory. Default: Current Directory.")

cli.addOptions(deploy)

do {
  try cli.parse()
} catch {
  cli.printUsage(error)
  exit(EX_USAGE)
}

if deploy.value {
	//TODO: empty path => current dir
	print (deploy.value)
}

```

How can I recognize that the deploy option was called but with an empty value ?
I want to support both : Giving a specific directory or leaving the directory path blank which should result in using the current directory. The only way I can think of is to make two options, one StringOption and one BoolOption. 

Is there any better chance to implement this behaviour ?

Thanks,
David

**Comment by beltex** [comment]
Hello @dehlen!

`StringOption` requires input if called, thus you will get an error on empty input.

```sh
$ tool -d
Invalid value(s) for option -d, --deploy:

Usage: tool [options]
  -d, --deploy:
      Deploys a plugin, color scheme or template from given directory. Default: ...
```

The user would have to pass in `""` like so `tool -d ""` to get the empty input behaviour. Here's some sample code for that:

```swift
// Same code as you listed except for the last bit

// ...

 // We have to unwrap the optional first
if let userPath = deploy.value where userPath.characters.count > 0 {
    print (userPath)
}
else if deploy.wasSet {
    // Current dir - will need to 'import Foundation' for this
    print(NSFileManager.defaultManager().currentDirectoryPath)
}
```

Hope that helps!

**Comment by dehlen** [comment]
The solution is not very satisfying. In my opinion the user experience would be very bad when the user needs to provide "" in order to deploy from the current directory. There should be the possibility to create an option with an optional parameter. 

For example tool -d or tool-d path. 

Do you share my opinion ? Then a feature request would be a good idea.

Cheers,
David

**Comment by beltex** [comment]
Sorry about the late response!

> The solution is not very satisfying. In my opinion the user experience would be very bad when the user needs to provide "" in order to deploy from the current directory.

I definitely agree that it is not the best user experience. What you originally mentioned of using two options, `StringOption` and `BoolOption`, is much cleaner and clearer, and I believe the most common approach to the problem. 

> There should be the possibility to create an option with an optional parameter.

In general, I would say that each command line option should only perform one action, so overloading a single option to both switch on an action (`BoolOption` - deploys a plugin in this case), and taking input (`StringOption` - a path), is against CLI design as I understand it. It could even be argued that `""` should not even be allowed for `StringOption` for the sake of consistency.

> Do you share my opinion ?

Nonetheless, just as we have a `strict` parameter for `parse()` to not allow unrecognized arguments, an additional parameter for strict parsing of **input** _could_ be added as well, such that the API user could turn it off to handle things in a custom manner. Thus, exceptions would not be thrown on empty input, and instead we just leave the `value` property as `nil`, but set `wasSet` to `true`, which would apply for all `Option` subclasses that take input. Thats one possible rough idea.

> Then a feature request would be a good idea.

I'd be happy to submit a pull request if there is consensus on this.

**Comment by beltex** [comment]
Just realized there is another possibility here via a stray value. See #23.

**Comment by jatoben** [comment]
@dehlen Sorry for being late to the party here. Do you need to specify `-d` if there's no argument? I would make the option non-required:

```swift
let deploy = StringOption(shortFlag: "d", longFlag: "deploy", required: false,
  helpMessage: "Deploys from given directory; default current directory"
```

Then just fetch the current directory if it wasn't specified:

```swift
let directory = deploy.wasSet ? deploy.value! : String.fromCString(getwd(nil))!
```

**Comment by jatoben** [comment]
@dehlen Hopefully this has been addressed, either with my suggestion :point_up: or via the stray values support added in #56. Please re-open if that's not the case.
