### ISSUE TITLE
ANSI color for ParseError.description & printUsage()

### ISSUE THREAD

**Issue by beltex** [jatoben/CommandLine#33]
Just a nice to have, nothing critical! :)

Have an option for the `CommandLine` class to turn on ANSI color. This would apply to error messages (`ParseError.description`), which could be in red for example, and to `printUsage()`, in which color is applied to `shortFlag`, `longFlag`, and the `helpMessage` (`Usage` line too?). Here's an example of what that might look like.

<img width="467" alt="dshb-ansi-color" src="https://cloud.githubusercontent.com/assets/2666961/9707215/057bcfaa-54ce-11e5-9551-a2e1e0e9986e.png">

This just requires pre-appending a print statement with an escape code to turn on a particular color, and appending the off code. If there is interest in adding this I'd be happy to submit a pull request.

**Comment by jatoben** [comment]
This looks like it could be a nice addition, I'd be interested in a PR :+1:
