### ISSUE TITLE
Usage for build phase

### ISSUE THREAD

**Issue by JiriTrecak** [jatoben/CommandLine#36]
Hello,

First, thanks for this truly masterful piece of code!

I wanted to know if there is any way how to use those parameters in XCode build phase, if you add your command as a new run script phase. I am able to run it easily from the commandline using swift + parameters, but I am not sure how to run it from the build script. I've used following:

    "$LAURINE_PATH" - -i "$SOURCE_PATH" -d "$DELIMITER" > "$OUTPUT_PATH"

And that is buildable, but does not seem to produce any output (command line does). Maybe it is something worth updating in the documentation as well.

Thank you!

**Comment by jatoben** [comment]
Thanks for the kind words! I'm not aware of any trouble using the `CommandLine` code in an Xcode build script, although I haven't tried it myself.

What output are you expecting to receive from that command? I took a look at https://github.com/JiriTrecak/Laurine, but I wasn't quite sure what should be happening in the build script.

**Comment by JiriTrecak** [comment]
I resolved the problem myself. I don't know what is up with ">" output pipe but apparently, it just does not work great when you use it with combination of my script, your script and also XCode. Or I did something wrong, I could not really tell. So what I did is to rewrite whole I/O of the script so it takes everything as parameter through commandline and now it works wonders, in command line and also in build script. You can try it, readme and everything is up so no more guessing!

Once again, thank you for your library, it will be used heavily and I intend to use it in more projects in the future. If you would like to refer this project in "who is it using" section, I would be more than happy.

Keep up good work!

Jiri

**Comment by jatoben** [comment]
Great, glad to hear you got things working!
