### ISSUE TITLE
Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by OKNoah** [jatoben/CommandLine#5]
I get this error when running:

```dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/USERNAME/Library/Developer/Xcode/DerivedData/LocaleShots-CLI-gncnoendtwgqeofpgzeuqazdgxau/Build/Products/Debug/CommandLine.framework/Versions/A/CommandLine
  Reason: image not found
(lldb) ```

There is some help here: http://stackoverflow.com/a/26383255/2183008

**Comment by colemancda** [comment]
You can create a bundle to hold the Swift standard libraries. 

http://colemancda.github.io/programming/2015/02/12/embedded-swift-frameworks-osx-command-line-tools/

**Comment by jatoben** [comment]
That's a very clever workaround @colemancda!

IMO for now though, the cleanest way to integrate CommandLine is by using git submodules, as @beltex  described. I'm going to close this for now; we'll see what future Swift revisions bring.

**Comment by tadman** [comment]
That helpful blog post link has changed, it's now: http://colemancda.github.io/2015/02/12/embedded-swift-frameworks-osx-command-line-tools

Just putting that here since this issue ranks pretty high for this particular type of problem. Thanks for the advice!
