### ISSUE TITLE
No Package.swift file found

### ISSUE THREAD

**Issue by n4ss** [jatoben/CommandLine#59]
Hi,

I’m currently using the swift package manager with your repo as a dependency and it seems that there is no 'Package.swift' file added in your version tags (none in the 3 versions).
Is this a choice or am I missing something?

`$ swift build`
`Cloning https://github.com/jatoben/CommandLine`
`Using version 2.0.0 of package CommandLine`
`error: No Package.swift file found at: /home/foo/bar/Packages/CommandLine-2.0.0/Package.swift`

Thanks,

**Comment by dduan** [comment]
Encountered the same issue. This could be solved by a new tag since there is a `Package.swift` on master.

**Comment by SleepyBrett** [comment]
Same issue.

**Comment by kfbishop** [comment]
Same here.   
@jatoben Please tag a new version that include Package.swift

**Comment by jatoben** [comment]
Tagged [2.2.0-pre1](https://github.com/jatoben/CommandLine/releases/tag/v2.2.0-pre1).
