### ISSUE TITLE
[Feature Request] git/pod sub command support

### ISSUE THREAD

**Issue by hewigovens** [jatoben/CommandLine#6]
It's nice to have sub commands support, like git add/commit, pod install etc...

**Comment by samskiter** [comment]
:+1: I just can't get this library integrated into my project setup. spent ages on it and giving up

**Comment by beltex** [comment]
Hello @samskiter!

See the bottom of the [README usage section](https://github.com/jatoben/CommandLine#usage),  #5, and #15. Remember, you can always simply copy the 3 source files into your project in Xcode via **Build Phases** > **Compile Sources** of your target. A step up from that would be to use a Git submodule, and then add to Xcode.

**Comment by Dschee** [comment]
@jatoben Great library, but I agree that subcommands would be great. I would have needed it right now, actually. ^^

Do you have any idea when 'near future' could be? :)

**Comment by Dschee** [comment]
I just implemented sub commands using CommandLine myself. You can see my implementation [here](https://github.com/Flinesoft/BartyCrouch/blob/stable/Sources/Code/SubCommander.swift). The usage can be seen [here](https://github.com/Flinesoft/BartyCrouch/blob/stable/Sources/Code/CommandLineParser.swift).

Maybe this helps to get this feature started or at least helps others implementing it themselves, too.

**Comment by jatoben** [comment]
This repository is being archived. See https://github.com/jatoben/CommandLine/issues/111.
