### ISSUE TITLE
Non-option parameters

### ISSUE THREAD

**Issue by Coder-256** [jatoben/CommandLine#62]
It would be nice if there was a way to specify at least one input file without an option. Here's an example with `cp`:

```
cp someFile.txt copiedFile.txt    # Copies someFile.txt to copiedFile.txt
```

And it would also be helpful to show that in the help text:

```
Usage:
./example [options] [file] file2 file3
```

It would also be great if these files could be optional (so, for example, the absence of a file causes the program to read from `stdin`).

**Comment by glessard** [comment]
You can use the `unparsedArguments` property to implement this

**Comment by jatoben** [comment]
This repository is being archived. See https://github.com/jatoben/CommandLine/issues/111.
