### ISSUE TITLE
XCode 7.3 + Swift 2.2 support

### ISSUE THREAD

**Issue by Dschee** [jatoben/CommandLine#63]
Now that XCode 7.3 was released with Swift 2.2 shipped by default I'm seeing the following issues when trying to install the latest commit on the master branch:

```
The following build commands failed:
	CompileSwift normal x86_64 /path/to/project/Carthage/Checkouts/CommandLine/CommandLine/StringExtensions.swift
	CompileSwift normal x86_64 /path/to/project/Carthage/Checkouts/CommandLine/CommandLineTests/CommandLineTests.swift
	CompileSwift normal x86_64 /path/to/project/Carthage/Checkouts/CommandLine/CommandLine/Option.swift
	CompileSwift normal x86_64 /path/to/project/Carthage/Checkouts/CommandLine/CommandLineTests/StringExtensionTests.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(5 failures)
```

Can we fix this?

**Comment by Dschee** [comment]
Here's some more information on where this actually might crash:

``` Swift
CommandLine.swift:19:2: error: unknown attribute 'exported'
@exported import Darwin
```

**Comment by jatoben** [comment]
Thanks for the report! I'm surprised by this though, `@exported` was removed in #46. Are you sure you're using the latest code from _master_?

**Comment by Dschee** [comment]
Ah sorry, forgot to close this issue. I already figured out that Carthage has a bug when updating specific dependencies. It's not an issue with CommandLine so I'm closing this. @jatoben Thank you for getting back to me anyways! :+1:
