### ISSUE TITLE
Convenience function to write to the same line

### ISSUE THREAD

**Issue by mathieutozer** [jatoben/CommandLine#84]
I'm trying to implement a progress indicator - it would be nice if the framework provided a way to write over the current line instead of printing on a new one.

**Comment by ahyattdev** [comment]
Is print("foo", terminator: "") too much?

**Comment by loganmoseley** [comment]
I think @mathieutozer wants to code the first image ([source](https://github.com/yamadapc/haskell-ascii-progress)), which does more than append, as opposed to the second image ([source](http://stackoverflow.com/questions/15477122/fixing-a-python-progress-bar-in-command-prompt)).

![bch0rjl](https://github.com/yamadapc/haskell-ascii-progress/raw/master/demo.gif)

![jkdsf](https://i.stack.imgur.com/SjEfU.jpg)

**Comment by jatoben** [comment]
This repository is being archived. See https://github.com/jatoben/CommandLine/issues/111.
