### ISSUE TITLE
Conversion from String to Double

### ISSUE THREAD

**Issue by barrypress** [jatoben/CommandLine#87]
Unlike the IntOption class, which uses the form 

    if let val = Int(values[0]) {

DoubleOption uses the toDouble String extension. Were it instead to use the form 

    if let val = Double(values[0]) {

the code base becomes slightly smaller, since toDouble can be deleted, and (more importantly) it becomes able to parse values in scientific notation.

Is there a reason I'm not seeing why it's this way? I've tried this change on a version prior to the rename to CommandLineKit, and it appears to work fine.

**Comment by jatoben** [comment]
@barrypress This dates from Swift 1, which didn't have an initializer for Double that took a String (cf. http://swiftdoc.org/v1.2/type/Double/).

> I've tried this change on a version prior to the rename to CommandLineKit, and it appears to work fine.

Sounds like a nice cleanup 😺 Want to go ahead and open a PR for this?

**Comment by barrypress** [comment]
Will do.

Barry

**Comment by jatoben** [comment]
Closed by #88.
