### ISSUE TITLE
Can't use with swiftpm at tag v2.2.0

### ISSUE THREAD

**Issue by glessard** [jatoben/CommandLine#89]
[some output omitted]
```
$ cd /tmp/
$ git clone https://github.com/jatoben/CommandLine
$ cd CommandLine
$ git checkout v2.2.0 -b 2.2.0
$ swift build
error: the module at Tests/CommandLine has an invalid name ('CommandLine'): the name of a test module has no ‘Tests’ suffix
fix: rename the module at ‘Tests/CommandLine’ to have a ‘Tests’ suffix
```

Please tag the repo more often; the current head works just fine and deserves a 2.2.1 tag!

**Comment by jatoben** [comment]
Fair point, although there have been some breaking changes in the move to Swift 3, like the rename to `CommandLineKit`. Would it be helpful to have a 3.0.0-pre tag for now? I'd like to make a few more cleanups before making a full 3.0.0 release.

**Comment by glessard** [comment]
"3.0.0-pre" wouldn't be usable by swiftpm either, as far as I know. Since there is a 2.2.0 tag now, incrementing that would good definitely be good. Having both tags is also a possibility!

**Comment by jatoben** [comment]
I tagged 3.0.0-pre1 and this works ok for me now:

```swift
let package = Package(
  name: "foo",
  dependencies: [
    .Package(url: "https://github.com/jatoben/CommandLine", Version("3.0.0-pre1")!),
  ]
)
```

@glessard Could you give that a try and let me know what you find?

**Comment by glessard** [comment]
I didn't know Version can take an arbitrary tag; this does work. The proper release will need to work with `.Package(url: "https://github.com/jatoben/CommandLine", majorVersion: 3)`, however.

**Comment by glessard** [comment]
For what it's worth, `.Package(url: "https://github.com/jatoben/CommandLine.git", Version(3,0,0, prereleaseIdentifiers: ["pre1"]))` also works.
