### ISSUE TITLE
Support blank spaces on file and path names?

### ISSUE THREAD

**Issue by Riccardo99** [jatoben/CommandLine#9]
`programm --files "path/my file.txt"` is getting two files on its options: `path/my` and `file.txt`as separated files. 

But "my file.txt" is only **one file** named "my file" and I only want this: `path/my file.txt`, **not this**: `path/my` **and** `file.txt`.

**Comment by Riccardo99** [comment]
Sorry, my bad: my shell script was messing up with my white spaces :-(

**Comment by jatoben** [comment]
No problem, thanks for the update!
