### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by TofPlay** [jatoben/CommandLine#95]
Below the title please add badges this help a lot. 

If your component is compatible: 
- with carthage add [![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-brightgreen.svg)](https://github.com/Carthage/Carthage)
- with SwiftPM add [![SwiftPM compatible](https://img.shields.io/badge/SwiftPM-compatible-brightgreen.svg)](https://github.com/apple/swift-package-manager)

Indicated:
- the Swift version ![Swift Version](https://img.shields.io/badge/Swift-3.0-orange.svg)
- Platforms supported ![Plaforms](https://img.shields.io/badge/Platforms-Linux%20%7C%20macOS%20%7C%20iOS%20%7C%20WatichOS%20%7C%20tvOS-lightgrey.svg)
- License ![License MIT](https://img.shields.io/badge/License-MIT-lightgrey.svg) 

You can take inspiration from this template for iOS [iOS-readme-template](https://goo.gl/EfA9zG)

**Comment by jatoben** [comment]
This repository is being archived. See https://github.com/jatoben/CommandLine/issues/111.
